### ISSUE TITLE
里面的thinkphp核心文件没有

### ISSUE THREAD

**Issue by jiwei3187553** [guaosi/tp5-newsapp#1]
thinkphp核心文件没有，是tp5.1的rc哪个版本的？

**Comment by guaosi** [comment]
composer.json文件里面有说明了包，一般不会把框架核心文件传上来
在项目目录下运行
composer install
会自动安装依赖
composer了解一下。

**Comment by guaosi** [comment]
composer.json文件里面有说明了包，一般不会把框架核心文件传上来
在项目目录下运行
composer install
会自动安装依赖
composer了解一下。
版本是thinkphp5.0.10
